Update cartridge and metrics versions
tarantool/cartridge-cli pull request #740
Opened 2022-11-23 13:42 UTC by yngvar-antonsson

- [ ] Tests
- [ ] Changelog
- [ ] Documentation

2022-11-23 13:47 UTC, DifferentialOrange approved these changes
It would be nice to put documentation and dependencies updates to separate commits, but this is fine too.

2022-11-24 15:37 UTC, LeonidVas requested changes
Hi! Thank you for the patchset.
We are decorate the commit messages according to https://github.com/tarantool/tarantool/wiki/Code-review-procedure#commit-message
"Update cartridge and metrics versions" -> "app-dependency: update cartridge and metrics"
"Update getting-started-app docs" -> "documentation: update getting-started-app"

2022-11-24 15:37 UTC, LeonidVas commented on CHANGELOG.md
> +## Unreleased
[Unreleased]

2022-11-24 15:37 UTC, LeonidVas commented on CHANGELOG.md
> +### Changed
Add an empty line after ([Unreleased]).

2022-11-25 13:33 UTC, LeonidVas approved these changes

2022-11-25 13:33 UTC, merged